### PR TITLE
Fix #2034

### LINKED ISSUE #2034: spdlog v1.9.1 and clang 12.0.1 (libc++) compilation failure
I cannot seem to compile any code that includes spdlog with clang 12.0.1.

```
#include <spdlog/spdlog.h>

int
main(int /*argc*/, char** /*argv*/)
{
    spdlog::info("Welcome to spdlog!");
    return 0;
}
```

```
/usr/bin/clang++ -std=c++20 -stdlib=libc++ -ggdb3 -pedantic-errors -Wall -Werror -Wextra -O0 -DSPDLOG_COMPILED_LIB -isystem/tmp/spdlog/1.9.1/include -c main.cpp
-o main.o
In file included from main.cpp:1:
In file included from /tmp/spdlog/1.9.1/include/spdlog/spdlog.h:12:
In file included from /tmp/spdlog/1.9.1/include/spdlog/common.h:7:
In file included from /tmp/spdlog/1.9.1/include/spdlog/details/null_mutex.h:6:
In file included from /usr/bin/../include/c++/v1/atomic:579:
In file included from /usr/bin/../include/c++/v1/__threading_support:15:
In file included from /usr/bin/../include/c++/v1/chrono:829:
/usr/bin/../include/c++/v1/type_traits:1688:66: error: call to consteval function 'fmt::basic_format_string<char>::basic_format_string<fmt::basic_string_view<char>, 0>' is no
t a constant expression
    : public integral_constant<bool, __is_convertible_to(_T1, _T2)> {};
                                                                 ^
/tmp/spdlog/1.9.1/include/spdlog/common.h:141:41: note: in instantiation of template class 'std::is_convertible<const fmt::basic_string_view<char> &, fmt::basic_format_string
<char>>' requested here
    : std::integral_constant<bool, std::is_convertible<const T &, fmt::format_string<>>::value || is_convertible_to_wformat_string<T>::value>
                                        ^
/tmp/spdlog/1.9.1/include/spdlog/logger.h:107:52: note: in instantiation of template class 'spdlog::is_convertible_to_basic_format_string<const fmt::basic_string_view<char> &
>' requested here
                                                  !is_convertible_to_basic_format_string<const T &>::value,
                                                   ^
/tmp/spdlog/1.9.1/include/spdlog/logger.h:109:10: note: while substituting prior template arguments into non-type template parameter [with T = fmt::basic_string_view<char>]
    void log(source_loc loc, level::level_enum lvl, const T &msg)
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/spdlog/1.9.1/include/spdlog/logger.h:102:9: note: while substituting deduced template arguments into function template 'log' [with T = fmt::basic_string_view<char>, $1 =
 (no value)]
        log(loc, lvl, string_view_t{msg});
        ^
/usr/bin/../include/c++/v1/type_traits:1688:66: note: undefined constructor 'basic_format_string<fmt::basic_string_view<char>, 0>' cannot be used in a constant expression
    : public integral_constant<bool, __is_convertible_to(_T1, _T2)> {};
                                                                 ^
/tmp/spdlog/1.9.1/include/spdlog/fmt/bundled/core.h:2835:17: note: declared here
  FMT_CONSTEVAL basic_format_string(const S& s) : str_(s) {
In file included from main.cpp:1:
In file included from /tmp/spdlog/1.9.1/include/spdlog/spdlog.h:12:
In file included from /tmp/spdlog/1.9.1/include/spdlog/common.h:7:
In file included from /tmp/spdlog/1.9.1/include/spdlog/details/null_mutex.h:6:
In file included from /usr/bin/../include/c++/v1/atomic:579:
In file included from /usr/bin/../include/c++/v1/__threading_support:15:
In file included from /usr/bin/../include/c++/v1/chrono:829:
/usr/bin/../include/c++/v1/type_traits:1688:66: error: call to consteval function 'fmt::basic_format_string<char>::basic_format_string<char [19], 0>' is not a constant expression
    : public integral_constant<bool, __is_convertible_to(_T1, _T2)> {};
                                                                 ^
/tmp/spdlog/1.9.1/include/spdlog/common.h:141:41: note: in instantiation of template class 'std::is_convertible<char const (&)[19], fmt::basic_format_string<char>>' requested here
    : std::integral_constant<bool, std::is_convertible<const T &, fmt::format_string<>>::value || is_convertible_to_wformat_string<T>::value>
                                        ^
/tmp/spdlog/1.9.1/include/spdlog/logger.h:107:52: note: in instantiation of template class 'spdlog::is_convertible_to_basic_format_string<char const (&)[19]>' requested here
                                                  !is_convertible_to_basic_format_string<const T &>::value,
                                                   ^
/tmp/spdlog/1.9.1/include/spdlog/logger.h:109:10: note: while substituting prior template arguments into non-type template parameter [with T = char [19]]
    void log(source_loc loc, level::level_enum lvl, const T &msg)
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/spdlog/1.9.1/include/spdlog/logger.h:95:9: note: while substituting deduced template arguments into function template 'log' [with T = char [19], $1 = (no value)]
        log(source_loc{}, lvl, msg);
        ^
/tmp/spdlog/1.9.1/include/spdlog/logger.h:246:9: note: in instantiation of function template specialization 'spdlog::logger::log<char [19]>' requested here
        log(level::info, msg);
        ^
/tmp/spdlog/1.9.1/include/spdlog/spdlog.h:255:27: note: in instantiation of function template specialization 'spdlog::logger::info<char [19]>' requested here
    default_logger_raw()->info(msg);
                          ^
main.cpp:7:13: note: in instantiation of function template specialization 'spdlog::info<char [19]>' requested here
    spdlog::info("Welcome to spdlog!");
            ^
/usr/bin/../include/c++/v1/type_traits:1688:66: note: undefined constructor 'basic_format_string<char [19], 0>' cannot be used in a constant expression
    : public integral_constant<bool, __is_convertible_to(_T1, _T2)> {};
                                                                 ^
/tmp/spdlog/1.9.1/include/spdlog/fmt/bundled/core.h:2835:17: note: declared here
  FMT_CONSTEVAL basic_format_string(const S& s) : str_(s) {
                ^
2 errors generated.
```

spdlog was built using the following cmake command
```
cmake \
        -DCMAKE_BUILD_TYPE:STRING=Release \
        -DCMAKE_CXX_COMPILER:STRING=/usr/bin/clang++ \
        -DCMAKE_CXX_FLAGS:STRING="-stdlib=libc++ -rtlib=compiler-rt -fuse-ld=lld -lgcc_s" \
        -DCMAKE_INSTALL_PREFIX:PATH=/tmp/spdlog/1.9.1 \
        -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
        -DSPDLOG_BUILD_SHARED:BOOL=OFF \
        -S . -B _build
```

Any help would be appreciated. Thanks!

### PR DESCRIPTION
**Pull request by dkavolis**
For some reason clang doesn't like a disabled constructor in `std::is_convertible` so conversion to format strings has to be replaced by conversion to equivalent string views as in `fmt`.

This time also tested with Clang 12.0.1 C++20. Might be a good idea to add C++20 to CI.

Fixes #2034

### CODE REVIEW

**Comment by boxerab** [comment]
@dkavolis thank you! this patch fixed errors I started getting from clang 12 and c++20 after updating to latest v1.x version.

File: include/spdlog/common.h [hunk 1]
```diff
@@ -116,16 +116,27 @@ using wstring_view_t = fmt::basic_string_view<wchar_t>;
...
 #        error SPDLOG_WCHAR_TO_UTF8_SUPPORT only supported on windows
 #    else
 template<typename T>
 struct is_convertible_to_wstring_view : std::is_convertible<T, wstring_view_t>
 {};
+
 template<class T>
-struct is_convertible_to_wformat_string : std::is_convertible<T, fmt::wformat_string<>>
-{};
+using is_convertible_to_wformat_string = is_convertible_to_basic_format_string<T, wchar_t>;
```
Comment (gabime) [inline include/spdlog/common.h:139]: Does it compile if SPDLOG_WCHAR_TO_UTF8_SUPPORT (and hence is_convertible_to_wformat_string ) are not defined ?

Anyway I think it is cleaner just to remove the ```is_convertible_to_wformat_string``` definitions completely (lines 134-147) and do something like:

```c++
template<class T>
struct is_convertible_to_any_format_string
    : std::integral_constant<bool, is_convertible_to_basic_format_string<T, char>::value || is_convertible_to_basic_format_string<T, wchar>::value>
{};
```

**Review by gabime — CHANGES_REQUESTED** [review]

File: include/spdlog/common.h (hunk 1 above)
Comment (dkavolis) [reply include/spdlog/common.h:139]: `is_convertible_to_wformat_string` is defined the same way as `is_convertible_to_wstring_view` but a quick search in the repo showed no uses of either outside of `logger::log` SFINAE check if `msg` is convertible to a string view or format string. I used `is_convertible_to_wstring_view` as an example for `is_convertible_to_wformat_string` since they are both very similar. Might be cleaner to remove both in this case.

Comment (gabime) [reply include/spdlog/common.h:139]: yes. please remove them

**Comment by dkavolis** [comment]
Also removed the SFINAE check for string view conversion in `logger::log` since format strings already check for it.

**Comment by gabime** [comment]
Thanks @dkavolis

**Comment by gabime** [comment]
@dkavolis I added CI to test c++20 but it fails here: https://travis-ci.com/github/gabime/spdlog/jobs/530329470

Could you please take a look please? (I tried fixing with wrapping with fmt::runtime the problematic line but it didn't help)

**Comment by dkavolis** [comment]
Seems like an issue with clang, the error happens when using `std::strlen` at compile time
```cpp
  FMT_CONSTEXPR_CHAR_TRAITS
  FMT_INLINE
  basic_string_view(const Char* s) : data_(s) {
    if (detail::const_check(std::is_same<Char, char>::value &&
                            !detail::is_constant_evaluated()))
      size_ = std::strlen(reinterpret_cast<const char*>(s));
    else
      size_ = std::char_traits<Char>::length(s);
  }
```
But the only way this can happen is if either `__cpp_lib_is_constant_evaluated` is undefined, `std::is_constant_evaluated()` returns false or clang tries to evaluate the discarded branch in constant expression, neither of which should happen.

Can it be due to the old libstdc++ version? GCC is only version 7.5.0 which has almost no C++20 features.
