### PR TITLE
Match SPDLOG_CONSTEXPR_FUNC to FMT_CONSTEXPR

### LINKED ISSUE #2856: Different use_constexpr definitions in spdlog and fmt causes compile time error in NVCC (and possibly other compilers)
# Description
When calling `logger.trace()` in an .cu file compiled using nvcc, I get the following compile time error:
~~~
spdlog/common.h:351:30: error: call to non-‘constexpr’ function ‘const T* fmt::v9::detail::buffer<T>::data() const [with T = char]’
  351 |     return spdlog::string_view_t{buf.data(), buf.size()};
      |                      ~~~~~~~~^~
~~~

# Cause
The [to_string_view](https://github.com/gabime/spdlog/blob/cedfeeb95f3af11df7d3b1e7e0d3b86b334dc23b/include/spdlog/common.h#L349) utility function is declared as [SPDLOG_CONSTEXPR_FUNC](https://github.com/gabime/spdlog/blob/cedfeeb95f3af11df7d3b1e7e0d3b86b334dc23b/include/spdlog/common.h#L72C19-L72C19). The functions calls [fmt::v9::detail::buffer<T>::data()](https://github.com/gabime/spdlog/blob/cedfeeb95f3af11df7d3b1e7e0d3b86b334dc23b/include/spdlog/fmt/bundled/core.h#L911) which is declared as [FMT_CONSTEXPR](https://github.com/gabime/spdlog/blob/cedfeeb95f3af11df7d3b1e7e0d3b86b334dc23b/include/spdlog/fmt/bundled/core.h#L95). However, FMT_CONSTEXPR has different conditions than SPDLOG_CONSTEXPR_FUNC and is defined to be empty for NVCC, leading to the data() function not declared as constexpr and thus causing the error.

# Fix
Adding the [same condition](https://github.com/gabime/spdlog/blob/cedfeeb95f3af11df7d3b1e7e0d3b86b334dc23b/include/spdlog/fmt/bundled/core.h#L95) to the definition of SPDLOG_CONSTEXPR_FUNC fixes the error. However, the two definitions need to be kept in sync in future changes.

Another potential fix is to declare the to_string_view functions as inline instead of constexpr.

### PR DESCRIPTION
**Pull request by kkraus14**
Fixes #2856.

PR based on #2858 and #2859.

Fixes the issue where a constexpr function in spdlog may call a non-constexpr function in fmt because `FMT_CONSTEXPR` is not defined or is defined differently for a given compiler.

Ideally, a test could be added of building a `.cu` file using nvcc and add that to CI to prevent nvcc breakages moving forward.

### CODE REVIEW

**Comment by kkraus14** [comment]
An alternative approach that might work here is to reuse `FMT_CONSTEXPR` with something like:
```cpp
#ifdef FMT_CONSTEXPR
    #define SPDLOG_CONSTEXPR_FUNC FMT_CONSTEXPR
#else
    #if __cplusplus >= 201402L
        #define SPDLOG_CONSTEXPR_FUNC constexpr
    #else
        #define SPDLOG_CONSTEXPR_FUNC inline
    #endif
#endif
```

This may be friendlier to when we're using `std::format` as opposed to `fmt` as well.

**Comment by gabime** [comment]
> An alternative approach that might work here is to reuse FMT_CONSTEXPR with something like

Agreed. Seems cleaner and to the point (use same constexpr as fmt).

File: include/spdlog/common.h [hunk 1]
```diff
@@ -65,14 +65,23 @@
...
+// depending on the compiler
+// If fmt determines it can't use constexpr, we should inline the function instead
+#ifdef SPDLOG_USE_STD_FORMAT
+    #define SPDLOG_CONSTEXPR_FUNC constexpr
+#else  // Being built with fmt
+    #if FMT_USE_CONSTEXPR
+        #define SPDLOG_CONSTEXPR_FUNC FMT_CONSTEXPR
     #else
-        #define SPDLOG_CONSTEXPR_FUNC inline
+	#define SPDLOG_CONSTEXPR_FUNC inline
```
Comment (kkraus14) [inline include/spdlog/common.h:84]: I needed to change this slightly to maintain the current behavior. If fmt determines it can't use constexpr then it defines `FMT_CONSTEXPR` as empty https://github.com/gabime/spdlog/blob/cedfeeb95f3af11df7d3b1e7e0d3b86b334dc23b/include/spdlog/fmt/bundled/core.h#L92-L107 while spdlog's current behavior is to define it as `inline`

Comment (kkraus14) [reply include/spdlog/common.h:84]: We could probably use some preprocessor magic to detect when `FMT_CONSTEXPR` is empty and use `inline` instead in those situations, but that adds some non-trivial complexity.

Comment (gabime) [reply include/spdlog/common.h:84]: Why would it be empty?

Comment (kkraus14) [reply include/spdlog/common.h:84]: It gets defined as empty for some reason: https://github.com/gabime/spdlog/blob/cedfeeb95f3af11df7d3b1e7e0d3b86b334dc23b/include/spdlog/fmt/bundled/core.h#L106

Comment (gabime) [reply include/spdlog/common.h:84]: I think it won't matter for spdlog. It can be empty for spdlog as well.

Comment (kkraus14) [reply include/spdlog/common.h:84]: Updated based on that

**Comment by kkraus14** [comment]
Looks like without the inline in C++11 (in C++14 and newer it would be constexpr) we hit some ODR violations from the header being included in multiple translation units that then get linked into a single artifact.

**Comment by gabime** [comment]
So  I guess we need to use your first suggestion after all.

**Comment by kkraus14** [comment]
Reverted the change where I think this should be good to go. Thanks for your review and feedback @gabime!

**Comment by gabime** [comment]
Thanks @kkraus14
