### PR TITLE
Fix deprecation warnings in filename_to_str and improve performance of wbuf_to_utf8buf

### LINKED ISSUE #569: VS 2017 Update 15.5: Build Error C4996
With update 15.5, MSVC has drastically changed the behaviour of the std::allocator. Just wanted to give you a heads-up:

`Error	C4996	'std::allocator<char>::allocate': warning STL4010: Various members of std::allocator are deprecated in C++17. Use std::allocator_traits instead of accessing these members directly. You can define _SILENCE_CXX17_OLD_ALLOCATOR_MEMBERS_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning.	...\include\spdlog\fmt\bundled\format.h	903	`

Lemme know if you need any more info.

### PR DESCRIPTION
**Pull request by sylveon**
This fixes #569

### CODE REVIEW

**Comment by gabime** [comment]
How does it solves the warning? seems to contain some changes  not related to the warning. 
Also, changing the signature  of  wbuf_to_utf8buf to return of allocated std::string instead of filling the given buffer is not good since the buffer already contains stack buffer ready to be filled, so no allocation is done.

**Comment by sylveon** [comment]
Yeah, it also generally improves wbuf_to_utf8buf. I'll push another commit with your suggested approach.

File: include/spdlog/details/os-inl.h [hunk 1]
```diff
@@ -398,28 +403,42 @@ SPDLOG_INLINE bool in_terminal(FILE *file) SPDLOG_NOEXCEPT
...
-    if (wbuf_size == 0)
+    if (wstr.size() > static_cast<size_t>(std::numeric_limits<int>::max()))
     {
+        throw spdlog::spdlog_ex("UTF-16 string is too big to be converted to UTF-8");
+    }
+
+    int wstr_size = static_cast<int>(wstr.size());
+    if (wstr_size == 0)
+    {
+        target.resize(0);
```
Comment (gabime) [inline include/spdlog/details/os-inl.h]: seems like redundant resize

Comment (sylveon) [reply include/spdlog/details/os-inl.h]: I added so that if somebody passes a previously used memory_buffer, it'll be correctly emptied instead of staying filled.

Comment (gabime) [reply include/spdlog/details/os-inl.h]: i meant the other resize , the one below

Comment (gabime) [reply include/spdlog/details/os-inl.h]: anyway, it would be interesting to compare the new performance. could you run your benchmark again?
