### PR TITLE
Fix #3525: Make level name matching case-insensitive

### LINKED ISSUE #3525: Loading log levels from env does not work with uppercase level names
Hi,

when I set the log levels names to be uppercase via SPDLOG_LEVEL_NAMES in tweakme.h, 
SPDLOG_INLINE void load_levels() does not work.
It calls to_lower_(lvl) on the level name from the environment, and then checks in from_str() whether this is equal to one of the string in SPDLOG_LEVEL_NAMES. This is always false, if the level names are not lowercase.

### PR DESCRIPTION
**Pull request by ssam18**
This fixes the issue where uppercase level names in environment variables weren't recognized. The from_str() function now does case-insensitive matching, so SPDLOG_LEVEL="DEBUG" works just like "debug". All existing tests pass plus new tests verify uppercase and mixed-case level names work correctly.

### CODE REVIEW

**Comment by tt4g** [comment]
Thank you for contribution but duplicate this PR: #3531

**Comment by SamareshSingh** [comment]
Hmm. I didn't realized it. Thanks for checking it

File: include/spdlog/common-inl.h [hunk 1]
```diff
@@ -29,15 +29,31 @@ SPDLOG_INLINE const char *to_short_c_str(spdlog::level::level_enum l) SPDLOG_NOE
...
 
 SPDLOG_INLINE spdlog::level::level_enum from_str(const std::string &name) SPDLOG_NOEXCEPT {
-    auto it = std::find(std::begin(level_string_views), std::end(level_string_views), name);
+    auto it = std::find_if(std::begin(level_string_views), std::end(level_string_views),
+                           [&name](const string_view_t &level_name) {
+                               return level_name.size() == name.size() &&
+                                      std::equal(name.begin(), name.end(), level_name.begin(),
+                                                 [](char a, char b) {
+                                                     return std::tolower(static_cast<unsigned char>(a)) ==
+                                                            std::tolower(static_cast<unsigned char>(b));
```
Comment (gabime) [inline include/spdlog/common-inl.h:38]: std::tolower requires include<cctype>

**Review by gabime — CHANGES_REQUESTED** [review]
