### PR TITLE
Fix UWP detection.

### LINKED ISSUE #3488: Detection of UWP platform
Hi,

This line:
https://github.com/gabime/spdlog/blob/cdbd64e2305a712ec9a360e5a1e05aa1dcab85e7/include/spdlog/details/os-inl.h#L570
is causing problems for us when compiling spdlog 1.1.6.0 for UWP without enabling /ZW. According to [this documentation](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/misc-info), it seems that detection of UWP platform should be done via the `WINAPI_FAMILY` macro:
```c++
#if (WINAPI_FAMILY == WINAPI_FAMILY_DESKTOP_APP)
    // Win32/Desktop code, including Windows App SDK code
#else
    // UWP code
#endif
```

### PR DESCRIPTION
**Pull request by jdumas**
Fixes #3488

### CODE REVIEW

File: include/spdlog/details/os-inl.h [hunk 1]
```diff
@@ -567,7 +567,7 @@ SPDLOG_INLINE filename_t dir_name(const filename_t &path) {
     #pragma warning(disable : 4996)
 #endif  // _MSC_VER
 std::string SPDLOG_INLINE getenv(const char *field) {
-#if defined(_MSC_VER) && defined(__cplusplus_winrt)
+#if defined(_MSC_VER) && (WINAPI_FAMILY != WINAPI_FAMILY_DESKTOP_APP)
```
Comment (gabime) [inline include/spdlog/details/os-inl.h]: Better is check if WINAPI_FAMILY defined:

#if defined(_MSC_VER) && defined(WINAPI_FAMILY) && (WINAPI_FAMILY != WINAPI_FAMILY_DESKTOP_APP)
// non-desktop MSVC code
#endif

**Review by gabime — CHANGES_REQUESTED** [review]

File: include/spdlog/details/os-inl.h (hunk 1 above)
Comment (jdumas) [reply include/spdlog/details/os-inl.h]: Hmm should we also check if WINAPI_FAMILY_DESKTOP_APP is defined then?

Comment (gabime) [reply include/spdlog/details/os-inl.h]: Not sure. What the docs say?

Comment (jdumas) [reply include/spdlog/details/os-inl.h]: Unclear. I cannot find any official doc aside from [this page](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/misc-info). That being said, it's unlikely one macro would be defined but not the other.

Comment (gabime) [reply include/spdlog/details/os-inl.h]: I guess checking them both is the safe thing

Comment (jdumas) [reply include/spdlog/details/os-inl.h]: Condition updated!

**Comment by gabime** [comment]
Thanks @jdumas
