### PR TITLE
Fix #3038

### LINKED ISSUE #3038: wstr_to_utf8buf throw exception
In "wstr_to_utf8buf" function, memory_buf_t 's size is a const value of 250, (wstr_size+1)*2 is less than 250, so there is no resizing of the result_size. In next WideCharToMultiByte call, this step went wrong.The last error is ERROR_INSUFFICIENT_BUFFER(122)(0x7A).
My test string is"OnPlayerStateChanged:state not changed 〈1〉叶心音的父亲遭人陷害入狱，男友不救反而出国，反而被他弟弟陆景霄救下。可她不知道就是男友陷害的父亲，而自己却已经爱上男友的弟弟！《总裁的金丝雀》,2,1", and can reproduce of this issue. 

wstr_to_utf8buf

### PR DESCRIPTION
**Pull request by Tomas-Zhu**
WideCharToMultiByte is a convert from unicode to utf8, utf8 can use one to four one-byte (8-bit) code units.So (wstr_size+1)*2 is wrong in sometime.

### CODE REVIEW

File: include/spdlog/details/os-inl.h [hunk 1]
```diff
@@ -450,7 +450,7 @@ SPDLOG_INLINE void wstr_to_utf8buf(wstring_view_t wstr, memory_buf_t &target) {
     }
 
     int result_size = static_cast<int>(target.capacity());
-    if ((wstr_size + 1) * 2 > result_size) {
+    if ((wstr_size + 1) * 4 > result_size) {
```
Comment (gabime) [inline include/spdlog/details/os-inl.h:453]: Line 442 should also be fixes then.

Comment (Tomas-Zhu) [reply include/spdlog/details/os-inl.h:453]: Get it,I push again,please review.

**Comment by gabime** [comment]
Thanks @Tomas-Zhu
